[package]
name = "mpz-ot-core"
version = "0.1.0-alpha.6"
edition = "2024"

[lints]
workspace = true

[lib]
name = "mpz_ot_core"

[features]
default = []
rayon = ["dep:rayon", "mpz-core/rayon", "itybity/rayon", "blake3/rayon"]
test-utils = []

[dependencies]
mpz-core.workspace = true
mpz-common = { workspace = true, features = ["future"] }
clmul.workspace = true
matrix-transpose.workspace = true

aes.workspace = true
blake3 = { workspace = true, features = ["serde"] }
cipher.workspace = true
rand.workspace = true
rand_core.workspace = true
rand_chacha.workspace = true
rayon = { workspace = true, optional = true }
curve25519-dalek = { workspace = true, features = ["serde", "rand_core"] }
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
derive_builder.workspace = true
itybity.workspace = true
opaque-debug.workspace = true
cfg-if.workspace = true
bytemuck = { workspace = true, features = ["derive"] }
futures = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
zerocopy = { workspace = true }

[dev-dependencies]
rstest.workspace = true
criterion.workspace = true
pretty_assertions.workspace = true

[[bench]]
name = "ot"
harness = false
