[package]
name = "mpz-ot"
version = "0.1.0-alpha.6"
edition = "2024"

[lints]
workspace = true

[lib]
name = "mpz_ot"

[features]
default = []
rayon = ["mpz-ot-core/rayon"]
ideal = ["mpz-common/ideal", "serde"]
test-utils = ["mpz-ot-core/test-utils", "mpz-common/test-utils"]

[dependencies]
mpz-core.workspace = true
mpz-common = { workspace = true, features = ["sync"] }
mpz-ot-core.workspace = true

async-trait.workspace = true
futures.workspace = true
rand.workspace = true
rand_core.workspace = true
rand_chacha.workspace = true
thiserror.workspace = true
itybity.workspace = true
opaque-debug.workspace = true
serde = { workspace = true, optional = true }
serio.workspace = true
cfg-if.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
mpz-common = { workspace = true, features = [
    "test-utils",
    "ideal",
    "executor",
] }
mpz-ot = { workspace = true, features = ["ideal"] }
mpz-ot-core = { workspace = true, features = ["test-utils"] }
rstest = { workspace = true }
criterion = { workspace = true, features = ["async_tokio"] }
tokio = { workspace = true, features = [
    "net",
    "macros",
    "rt",
    "rt-multi-thread",
] }

[[bench]]
name = "shared"
harness = false

[[bench]]
name = "ferret_sender"
harness = false

[[bench]]
name = "ferret_receiver"
harness = false
