[package]
name = "mpz-wasm-bench"
version = "0.1.0-alpha.6"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mpz-garble-core = { workspace = true }
mpz-garble = { workspace = true }
mpz-zk-core = { workspace = true, features = ["rayon"] }
mpz-zk = { workspace = true, features = ["rayon"] }
pollster = { workspace = true }
mpz-circuits = { workspace = true, features = ["aes"] }
mpz-memory-core = { workspace = true }
mpz-core = { workspace = true }
mpz-common = { workspace = true, features = ["test-utils"] }
mpz-ot = { workspace = true, features = ["ideal", "rayon"] }
mpz-ot-core = { workspace = true, features = ["rayon"] }
mpz-vm-core = { workspace = true }
blake3 = { workspace = true }

wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
getrandom = { workspace = true, features = ["wasm_js"] }
rand = { workspace = true }
futures = { workspace = true }
web-spawn = { workspace = true, features = ["no-bundler"] }
rayon = { workspace = true }
web-sys = { workspace = true, features = [
    "console",
    "Window",
    "Performance",
    "Worker",
    "WorkerOptions",
    "WorkerType",
] }
serio = { workspace = true }
aes-wasm = { workspace = true }
aes = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chromiumoxide = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "process", "net", "io-util"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
futures = { workspace = true }
hyper = { workspace = true, features = ["server", "http1"] }
hyper-util = { workspace = true, features = ["tokio"] }
http-body-util = { workspace = true }
mime_guess = { workspace = true }

[[bin]]
name = "wasm-bench-runner"
path = "src/bin/runner.rs"
required-features = []
