[package]
name = "mpz-zk-core"
version = "0.1.0-alpha.6"
edition = "2024"

[lints]
workspace = true

[features]
default = []
rayon = ["dep:rayon", "mpz-core/rayon", "blake3/rayon", "itybity/rayon"]

[dependencies]
mpz-core = { workspace = true }
mpz-circuits = { workspace = true }
mpz-memory-core = { workspace = true }

thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
blake3 = { workspace = true, features = ["serde"] }
cfg-if = { workspace = true }
rangeset = { workspace = true, features = ["serde"] }
rayon = { workspace = true, optional = true }
itybity = { workspace = true }
zerocopy = { workspace = true }
rand_chacha = { workspace = true }

[dev-dependencies]
mpz-circuits = { workspace = true, features = ["aes"] }
mpz-ot-core = { workspace = true, features = ["test-utils"] }
rand = { workspace = true }
criterion = { workspace = true }
aes = { workspace = true }
rstest = { workspace = true }

[[bench]]
name = "prover"
harness = false

[[bench]]
name = "verifier"
harness = false
